# Generated by Django 4.2.1 on 2023-05-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="image",
        ),
        migrations.RemoveField(
            model_name="article",
            name="location",
        ),
        migrations.RemoveField(
            model_name="article",
            name="original_price",
        ),
        migrations.RemoveField(
            model_name="article",
            name="reduced_price",
        ),
        migrations.RemoveField(
            model_name="article",
            name="sector",
        ),
        migrations.AddField(
            model_name="article",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="details about the article and the promotion",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="image_link",
            field=models.URLField(
                blank=True,
                help_text="url to the product image, found in the provider website.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="new_price",
            field=models.FloatField(
                blank=True, help_text="Price of the article after reduction", null=True
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="old_price",
            field=models.FloatField(
                blank=True, help_text="Price of the article before reduction", null=True
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="type",
            field=models.CharField(
                choices=[
                    ("food", "Food"),
                    ("clothes", "Clothes"),
                    ("self-care", "Self Care"),
                    ("appliances", "Appliances"),
                    ("cosmetics", "Cosmetics"),
                    ("other", "Other"),
                ],
                default=None,
                help_text="Sector the product belongs to.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Url of the article in the provider website",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Name of the article as scrapped from the provider website.",
                max_length=255,
                null=True,
            ),
        ),
    ]
