# Generated by Django 4.2.1 on 2023-05-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_remove_article_image_remove_article_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="details about the article and the promotion",
                null=True,
            ),
        ),
    ]
