# Generated by Django 4.2.1 on 2023-06-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_item_delete_article"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="provider",
            new_name="link_to_provider",
        ),
        migrations.AddField(
            model_name="item",
            name="provider_name",
            field=models.CharField(
                blank=True,
                help_text="The item provider's name",
                max_length=20,
                null=True,
            ),
        ),
    ]
