# Generated by Django 4.2.1 on 2023-06-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0005_rename_provider_item_link_to_provider_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="livraison",
            field=models.CharField(
                blank=True,
                help_text="The item provider's delivery price",
                max_length=20,
                null=True,
            ),
        ),
    ]
