# Generated by Django 4.2.1 on 2023-06-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0006_item_livraison"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="online_payment",
            field=models.BooleanField(default=False),
        ),
    ]
