# Generated by Django 4.2.1 on 2023-07-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0007_item_online_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="last_updated_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
