# Generated by Django 4.2.3 on 2023-08-31 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("backend", "0009_alter_item_price_alter_item_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("food", "Food"),
                    ("clothes", "Clothes"),
                    ("self-care", "Self-care"),
                    ("appliances", "Appliances"),
                    ("cosmetics", "Cosmetics"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="ItemRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_sentiment",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the user likes the item. True for like. False for dislike.",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="backend.item"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("item", "user")},
            },
        ),
    ]
