# Generated by Django 4.2.3 on 2023-08-31 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0010_alter_item_category_itemrating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemrating",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rating",
                to="backend.item",
            ),
        ),
    ]
