# Generated by Django 4.2.3 on 2023-10-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0010_category_alter_item_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="static/images/"),
        ),
    ]
