# Generated by Django 4.2.3 on 2023-10-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0011_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_fr",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
