# Generated by Django 4.2.3 on 2023-09-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0011_alter_itemrating_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemrating",
            name="user_sentiment",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Whether the user likes the item. True for like. False for dislike.",
                null=True,
            ),
        ),
    ]
