# Generated by Django 4.2.3 on 2023-10-12 19:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0012_category_name_en_category_name_fr"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="livraison",
            new_name="delivery",
        ),
    ]
