# Generated by Django 4.2.3 on 2023-10-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0013_rename_livraison_item_delivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="delivery",
            field=models.CharField(
                blank=True,
                choices=[
                    ("available", "available"),
                    ("not available", "not available"),
                    ("with conditions", "with conditions"),
                ],
                help_text="The item provider's delivery price",
                max_length=20,
                null=True,
            ),
        ),
    ]
