# Generated by Django 4.2.3 on 2023-10-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0014_alter_item_delivery"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="The shop's name",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, help_text="Url to shop", null=True),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="static/images/"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="item",
            name="link_to_provider",
        ),
        migrations.RemoveField(
            model_name="item",
            name="provider_name",
        ),
    ]
