# Generated by Django 4.2.3 on 2023-10-20 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0015_shop_remove_item_link_to_provider_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="backend.shop",
            ),
        ),
    ]
