# Generated by Django 4.2.3 on 2023-11-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0016_item_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="score",
            field=models.FloatField(
                blank=True,
                default=1,
                help_text="Evaluation of category importance. Affects display order",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="score",
            field=models.FloatField(
                blank=True,
                default=1,
                help_text="Evaluation of offers on shop. Affects display order",
                null=True,
            ),
        ),
    ]
