# Generated by Django 4.2.3 on 2024-03-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0019_category_parent_alter_item_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_predictor_id",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="The category id returned by the predictor",
                null=True,
            ),
        ),
    ]
