# Generated by Django 4.2.3 on 2024-03-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0020_category_category_predictor_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_predictor_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="The category id returned by the predictor",
                max_length=20,
                null=True,
            ),
        ),
    ]
